### ISSUE TITLE
JS export requires an empty "js" directory inside export directory to work the first time

### ISSUE THREAD

**Issue by aladage** [deg-skeletor/skeletor-plugin-rollup#12]

**Comment by scheul93** [comment]
Cannot replicate with the skeletor sample project. I tried to recreate using the following steps

1. switch to `react-app` branch of sample project
2. ran `npm install` to pull down most recent
3. deleted `dist` directory where config was setup to output JS to
4. ran `skel export`

It created the `dist/js` directory, completed the export and added the bundled js files.

@aladage , can you post your js export config and what version of the plugin you were using?

**Comment by scheul93** [comment]
Talked to Aaron and showed him what I was doing using the sample project. Could not replicate, so closing ticket
