### ISSUE TITLE
Clearing write directory when re-bundling

### ISSUE THREAD

**Issue by scheul93** [deg-skeletor/skeletor-plugin-rollup#15]
Currently, the plugin does not clear the write directory when re-bundling. This can lead to older deprecated bundles being left in the directory.

For project maintenance sake, it would be better if the plugin cleared out the write directory first.

**Comment by heaper** [comment]
This can be accomplished with rollup plugins like [rollup-plugin-delete](https://www.npmjs.com/package/rollup-plugin-delete). Closing this ticket, but I'll add a ticket to the relevant orko templates.
